var http = require('http');
var path = require('path');
var express = require('express');
var compression = require('compression');
var app = express();
app.disable('x-powered-by');
app.use(compression());
app.use(express.static(path.join(__dirname, 'favicon')));
app.use(express.static(path.join(__dirname, 'public')));
var port = process.env.PORT || 9888;
http.createServer(app).listen(port);
console.log('itforedrag.dk listening on: http://localhost:' + port);